/**
 * The committed icons are the ones `icons.ts` draws (27.24).
 *
 * Five PNGs in `web/public/` that nothing else reads and no test looks at: exactly the files that
 * rot. The point of generating them was that their provenance is checkable, and this is the check
 * — without it "generated by tools/icons.ts" is a claim in a comment.
 *
 * It also pins the drawing. A change to the mark is fine and should be deliberate: this goes red,
 * you look at the icon, you run `deno task icons`, you commit both.
 */

import { assertEquals } from "jsr:@std/assert@^1";
import { ICONS, png } from "./icons.ts";

const dir = new URL("../web/public/", import.meta.url);

for (const icon of ICONS) {
  Deno.test({
    name: `27.24 -- ${icon.name} is what tools/icons.ts draws`,
    permissions: { read: ["."] },
    async fn() {
      const committed = await Deno.readFile(new URL(icon.name, dir));
      const drawn = await png(icon);
      // Lengths first: comparing two multi-kilobyte arrays that differ prints every byte, and the
      // length alone is usually the whole story.
      assertEquals(committed.length, drawn.length, `${icon.name} is a different size`);
      assertEquals(committed, drawn, `${icon.name} differs; run \`deno task icons\``);
    },
  });
}
